apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: merge-schedule-action
  title: merge-schedule-action
  annotations:
    github.com/project-slug: geolonia/merge-schedule-action


spec:
  type: library
  owner: user:default/smellman
  lifecycle: production
  # accessGrants:
  #   - team: group:geolonia/team-name
  #     permission: write  # read | triage | write | maintain | admin
